#author - TheDiVaZo
#Специально для https://votiverp.com

varsion: 1.0 #version of config

mysql:
  server_url: "jdbc:mysql://127.0.0.1:3306/simpsons"
  name: "Oleg"
  pass: "0000"
  dataSourceProperty:
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    #и другие...

rolls:
  defend:
    DEFAULT: 0 #ролл по умолчанию для всех.
    NETHERITE_ARMOR: 0 #+ролл за фулл незерит
    IRON_ARMOR: 0 #+ролл за фулл железо
    GOLDEN_ARMOR: 0 #+ролл за фулл золото
    LEATHER_ARMOR: 0 #+ролл за фулл кожу
    CHAINMAIL_ARMOR: 0 #+ролл за фулл кольчугу
    DIAMOND_ARMOR: 0 #+ролл за фулл алмазы
  attack:
    DEFAULT: 0
    HORSE: 0 #+ролл за лошадь.
  escape: #побег
    DEFAULT: 0
    HORSE: 0 #+ролл за лошадь.












